-- Add allergen columns to umbrella_ingredients table
ALTER TABLE public.umbrella_ingredients
  ADD COLUMN IF NOT EXISTS storage_area text,
  ADD COLUMN IF NOT EXISTS allergen_peanut boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS allergen_crustacean boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS allergen_treenut boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS allergen_shellfish boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS allergen_sesame boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS allergen_soy boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS allergen_fish boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS allergen_wheat boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS allergen_milk boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS allergen_sulphite boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS allergen_egg boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS allergen_gluten boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS allergen_mustard boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS allergen_celery boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS allergen_garlic boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS allergen_onion boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS allergen_nitrite boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS allergen_mushroom boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS allergen_hot_pepper boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS allergen_citrus boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS allergen_pork boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS allergen_custom1_name text,
  ADD COLUMN IF NOT EXISTS allergen_custom1_active boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS allergen_custom2_name text,
  ADD COLUMN IF NOT EXISTS allergen_custom2_active boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS allergen_custom3_name text,
  ADD COLUMN IF NOT EXISTS allergen_custom3_active boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS allergen_notes text;

-- Update the umbrella_ingredients_with_details view to include the new columns
CREATE OR REPLACE VIEW public.umbrella_ingredients_with_details AS
SELECT
  ui.id,
  ui.created_at,
  ui.updated_at,
  ui.organization_id,
  ui.name,
  ui.description,
  ui.major_group,
  ui.category,
  ui.sub_category,
  ui.storage_area,
  ui.primary_master_ingredient_id,
  ui.allergen_peanut,
  ui.allergen_crustacean,
  ui.allergen_treenut,
  ui.allergen_shellfish,
  ui.allergen_sesame,
  ui.allergen_soy,
  ui.allergen_fish,
  ui.allergen_wheat,
  ui.allergen_milk,
  ui.allergen_sulphite,
  ui.allergen_egg,
  ui.allergen_gluten,
  ui.allergen_mustard,
  ui.allergen_celery,
  ui.allergen_garlic,
  ui.allergen_onion,
  ui.allergen_nitrite,
  ui.allergen_mushroom,
  ui.allergen_hot_pepper,
  ui.allergen_citrus,
  ui.allergen_pork,
  ui.allergen_custom1_name,
  ui.allergen_custom1_active,
  ui.allergen_custom2_name,
  ui.allergen_custom2_active,
  ui.allergen_custom3_name,
  ui.allergen_custom3_active,
  ui.allergen_notes,
  fcg.name AS major_group_name,
  fc.name AS category_name,
  fsc.name AS sub_category_name,
  mi.recipe_unit_type,
  mi.cost_per_recipe_unit,
  ARRAY_AGG(uimi.master_ingredient_id) FILTER (WHERE uimi.master_ingredient_id IS NOT NULL) as master_ingredients
FROM
  umbrella_ingredients ui
  LEFT JOIN food_category_groups fcg ON ui.major_group = fcg.id
  LEFT JOIN food_categories fc ON ui.category = fc.id
  LEFT JOIN food_sub_categories fsc ON ui.sub_category = fsc.id
  LEFT JOIN master_ingredients mi ON ui.primary_master_ingredient_id = mi.id
  LEFT JOIN umbrella_ingredient_master_ingredients uimi ON ui.id = uimi.umbrella_ingredient_id
GROUP BY
  ui.id,
  fcg.name,
  fc.name,
  fsc.name,
  mi.recipe_unit_type,
  mi.cost_per_recipe_unit;